### ISSUE TITLE
Display problems with Symbol created from Framer's built-in Android Kit

### ISSUE THREAD

**Issue by gnyrd** [der-lukas/framer-Symbols#8]
I've linked to a project that shows the problem.

Steps to reproduce:

 - Create a new Android Kit project from Framer's Welcome screen.

 - Add Symbols module

- create a new symbol from the qwerty keyboard in the Design tab

- display the new symbol

https://framer.cloud/ARrHm

**Comment by der-lukas** [comment]
The problem is that the layers inside a symbol need a "name", but the layers in this kit don't have a name. So when you for example just create a textLayer in design-mode the content of the layer is shown in the layerList, but it's not really a "name" for the layer yet. You have to manually change the name of the layer in the layerlist.

![image](https://user-images.githubusercontent.com/5270044/36963616-42c434c0-2054-11e8-963b-cafe05d7a609.png) 
The "1" is not a real "name" for the layer, but just a "placeholder"

<img width="287" alt="bildschirmfoto 2018-03-05 um 09 06 36" src="https://user-images.githubusercontent.com/5270044/36963680-8879d858-2054-11e8-96ea-13c918adf44c.png">
Manually changing the name sets the "name" prop of the layer.

Here's your updated prototype: https://framer.cloud/GoABO
