### ISSUE TITLE
Width of Symbol instance does not persist

### ISSUE THREAD

**Issue by gnyrd** [der-lukas/framer-Symbols#9]
Create a Symbol

Create an instance of that symbol and set a different width

Animate that symbol instance to a common state, the width reverts to the width of the original Design element.

https://framer.cloud/ixPsK

(also pls note the backspace is misbehaving when the width is changed)

**Comment by der-lukas** [comment]
Hey! I justed wanted to let you know that I‘m working on this. 

The goal I want to achieve is that:

* Props changed in the instance-declaration persist throughout all states
* Ability to change props for commonStates in addition to or instead of using a template

I‘m almost there but still have some issues, but you can expect those improvements in the next couple of days!

**Comment by der-lukas** [comment]
Hey @gnyrd!

I just pushed the changes stated above!
